language: node_js
node_js:
  - "10"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - yarn lint
  - ./cc-test-reporter before-build
  - yarn test
  - ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
